# Generated by Django 5.1 on 2026-07-28 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advising', '0002_remove_appointment_appointment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_mode',
            field=models.CharField(choices=[('In-Person', 'In-Person'), ('Virtual', 'Virtual')], default='In-Person', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='issue_category',
            field=models.CharField(choices=[('Academic Advising', 'Academic Advising'), ('Course Registration', 'Course Registration'), ('Graduation Audit', 'Graduation Audit'), ('Career Guidance', 'Career Guidance'), ('General Inquiry', 'General Inquiry')], default='Academic Advising', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
